/**
 * Whole-rubric multimodal rescoring prompt — Step 6 of the rubric verifier
 * pipeline.
 *
 * Rescores every criterion in a single LLM call given the action history,
 * the agent's predicted output, baseline (action-only) scores, and per-criterion
 * screenshot evidence. Produces post_image_earned_points per criterion.
 *
 * Variables:
 *   - task_definition              — instruction string
 *   - init_url_context             — "Starting URL: ..." or empty
 *   - action_history               — compact textual action history
 *   - agent_predicted_output       — agent's final answer / message
 *   - full_rubric_with_baselines   — rubric items + per-item baseline score
 *   - all_screenshot_evidence      — evidence grouped by criterion (Step 4
 *                                    output, or a fallback summary when Step 4
 *                                    hasn't run)
 *   - num_criteria                 — must match items.length in output
 *
 * Note: this version preserves the `$num_criteria_minus_1` token (used inside
 * the prompt as `{num_criteria_minus_1}`) so the model self-anchors on the
 * count from `num_criteria` and the example schema's "...one entry per
 * criterion..." instruction. We pass the count via `num_criteria` only.
 */
export const RUBRIC_RESCORING_PROMPT = `Task: $task_definition$init_url_context

**Action History:**
$action_history

**Agent's Predicted Output (Final Answer):**
$agent_predicted_output

**Full Rubric with Baseline (Action-Only) Scores:**
$full_rubric_with_baselines

**Screenshot Evidence Analyses (grouped by criterion):**
$all_screenshot_evidence

**Your Task:**
You are rescoring the ENTIRE rubric in a single pass based on the screenshot evidence, the agent's action history, and the agent's predicted output. For each criterion, determine whether the baseline (action-only) score should be adjusted based on the visual evidence.

**Reality Notes:**
- Some criteria may include a "Reality Notes" annotation just below their Description. These notes were generated by comparing the rubric's original assumptions against what the screenshots actually show. They provide interpretive context — clarifying, nuancing, or correcting the Description's **factual claims** in light of reality. When Reality Notes are present, they take precedence over the Description **only for conflicting factual claims** (e.g., what products exist, what a website actually shows, what options are available). However, Reality Notes do NOT override the Core Evaluation Principles below (cascading dependencies, uncontrollable blockers, best-effort evaluation, etc.).
- Reality Notes limitations: Reality Notes were generated from screenshot evidence ONLY — they did not have access to the Action History. For URL and navigation information, the **Action History is authoritative**.

**Agent Output Format:** The agent's predicted output above may be a structured dictionary (e.g., \`{"target_name": "...", "target_id": "...", "url": "..."}\`) rather than free-text prose. This is a valid and complete answer format. Information present in these fields counts as the agent having identified and presented that information. Do NOT penalize the agent for using a structured output format instead of prose.

**Core Evaluation Principles:**

**IMPORTANT**: These principles OVERRIDE the "description" field of individual rubric criteria when the description is more restrictive than these principles allow. The criterion descriptions are auto-generated and may contain overly strict language that conflicts with the fair-scoring principles below. When there is a conflict, follow these principles — not the criterion description.

1. **Best Effort Evaluation**: The agent should be evaluated on its helpfulness and effort within the constraints of external factors it cannot control. Award full credit when the agent demonstrates reasonable effort but is blocked by uncontrollable factors.

2. **Uncontrollable Blockers** (Award full credit when these prevent task completion):
   - Platform/infrastructure issues: Website down, blocked by CAPTCHA, login walls without credentials, server errors
   - Entity non-existence: Product discontinued, business closed, service unavailable
   - Availability constraints: Out of stock, no reservations available, sold out
   - Platform limitations: Platform doesn't list entity, platform requires critical point crossing (e.g., login required to add to cart)
   - Search result limitations: No results matching all specified criteria
   - IMPORTANT: If screenshots CONFIRM an uncontrollable blocker, you must award full credit for that criterion (and any dependent downstream criteria), regardless of the baseline score.

3. **Controllable Failures** (Should be penalized):
   - Wrong selections when correct options are available (wrong product, wrong date, wrong location)
   - Poor execution: Not using available filters, not attempting specified platforms
   - Hallucinations: Claiming success without evidence in Action History or screenshots
   - Insufficient effort: Giving up prematurely without reasonable attempt

4. **Tasks with Explicit Constraints**: When a task has explicit constraints (e.g., "requiring a Master's degree," "with at least 4.5 stars," "non-stop flights only"), distinguish between the agent **searching for** the constraint and actually **finding results that satisfy** it. The agent's effort to search is worth something, but the primary value is whether the constraint was actually met in the final answer.
   - Determine which constraints are **hard/primary** versus **soft/secondary**. Hard constraints typically include specific qualifications, product attributes, or explicit filtering criteria that the user called out.
   - If the agent searched for a hard constraint but the results do NOT actually satisfy it, award only minimal partial credit for the search effort — do NOT award substantial credit as if the constraint were satisfied.
   - Conversely, if the constraint IS satisfied in the evidence, award full or near-full credit even if the agent's search path was indirect.
   - **The key question is: does the agent's final output present a result that actually meets the hard constraints, supported by evidence?** Evidence can come from the agent's output text, the action history, OR what is visually apparent in screenshots.

5. **Ambiguous Data or Task Wording — Do Not Penalize for Picking One Valid Interpretation**: When a criterion or the task itself uses language that has multiple reasonable interpretations, or the underlying data is genuinely ambiguous, do NOT penalize the agent for picking one defensible interpretation and proceeding. As long as the agent's choice is defensible, award full credit.

6. **Subjective or Preference-Based Claims — Trust Reasonable Sources of Authority**: For inherently subjective claims (e.g., "find one of Beyoncé's favorite restaurants"), when the agent's selection is supported by a reasonable source of authority (search engine results, credible news articles, blog posts), award full credit. Do NOT demand definitive proof for claims that are inherently informal.

7. **CRITICAL: Handling Cascading Dependencies**:

   Distinguish between scenarios when evaluating dependent criteria:

   **Scenario A: DO NOT cascade penalties when blocked by uncontrollable factors.** If the agent is blocked by an uncontrollable factor that prevents completion of subsequent dependent criteria, award full credit for ALL dependent downstream criteria that could not be attempted.

   **Scenario B: DO cascade penalties for controllable failures.** If the agent makes a controllable error on an upstream criterion that prevents downstream criteria, penalize the upstream criterion and award partial or zero credit downstream.

   **Scenario C: DO NOT re-penalize for the same deviation across criteria.** Each criterion should evaluate what it uniquely measures — not repeat the penalty from another criterion. If criterion X penalizes for deviation D, criterion Y should evaluate the agent's work FOR THE DATA IT ACTUALLY FOUND — not re-penalize for the same upstream deviation.

   **Scenario D: Shared platform blockers across sibling criteria.** When a task involves multiple independent sub-tasks on the same platform and the agent discovers a platform-level blocker, the blocker applies to ALL sub-tasks. Award full credit for ALL sibling criteria affected by the shared blocker.

8. **Conditional Criteria**: Some criteria have a "condition" field. Criteria whose condition is NOT met have already been excluded from rescoring. For criteria whose condition IS met, score them normally.

9. **Alternative Source Usage with Transparency**: When a criterion requires finding info from a specific source: if the specified source has no relevant data or is inaccessible, and the agent uses an alternative source while clearly disclosing this, award partial credit — do NOT give zero credit. Only give zero credit if the agent silently uses an alternative source without disclosure, fabricates information, or provides irrelevant results.

10. **Distinguish nitpicks from critical errors when scoring**:

    A **nitpick** is a minor formatting, labeling, or precision difference that does not materially affect whether the agent satisfied the criterion's intent. A **critical error** is a substantive failure that means the criterion's core requirement was NOT met (wrong entity, hallucination, wrong action type, missing key requirement).

    A **correct approach, wrong answer** is when the agent demonstrates the right methodology but arrives at the wrong final result due to an execution mistake. Award partial credit for the demonstrated competence (typically 40-80% of max).

    Scoring guidance:
    - **Only nitpicks**: Award 75-100% of the criterion's max points
    - **Correct approach, wrong answer**: Award 40-80% of max points
    - **Critical error**: Penalize depending on severity
    - **Mix of nitpicks and a critical error**: Score based primarily on the critical error

**CRITICAL: Screenshots Are Chronologically Ordered — Always Trust the LATEST State:**

Screenshots are numbered in chronological order: Screenshot 1 is the earliest, and higher-numbered screenshots are later in time. When multiple screenshots show the same UI element with different values, the LATEST screenshot reflects the final state and MUST take precedence. Only penalize if the final/latest relevant screenshot still shows the wrong value.

**Re-scoring Guidelines:**

1. **Trust visual evidence over action history**: If screenshots contradict what the agent claimed, the visual evidence takes precedence. Always use the LATEST screenshot when multiple screenshots show the same element in different states.

2. **For criteria evaluating the agent's output**: Check if the predicted output addresses the criterion's requirements. Use screenshots to verify accuracy. Do NOT give zero credit simply because output text is not visible on screen — output is delivered as text, not rendered in a browser. Evaluate claims using these five categories:
   - **Contradiction** (penalize): Screenshots show X, agent claims not-X
   - **Fabrication** (penalize): Agent claims X with zero evidentiary basis
   - **Omission** (penalize): Agent didn't view what it needed to; X is commonly known to exist but agent didn't look
   - **Supported inference from absence** (do NOT penalize): Screenshots consistently show no evidence of X across all relevant pages, AND X is not commonly known to exist
   - **Visual confirmation without explicit statement** (do NOT penalize): Output omits justification but screenshots visually confirm the correct result

3. **Verify environment blockers**: If the agent claimed a blocker, screenshots must CONFIRM it. If not visible, penalize appropriately.

4. **Catch discrepancies**: If screenshots show information the agent missed or misinterpreted, penalize based on severity.

5. **Provide clear justification**: For each criterion, explain what changed between the baseline score and the new score based on visual evidence.

**Output Format:**
Output a JSON object with an "items" list. Each item corresponds to a criterion (in order), and must contain:
{{
  "items": [
    {{
      "criterion_idx": 0,
      "applicable_evidence": "Which screenshot evidence is applicable. When multiple screenshots show the same element, identify which is the LATEST. If no evidence is applicable, state that clearly.",
      "post_image_justification": "Reason about how the score should change based on the applicable evidence. If keeping the same score, explain why.",
      "post_image_earned_points": <number between 0 and max_points for this criterion>
    }},
    ...one entry per criterion, in order...
  ]
}}

You MUST output exactly $num_criteria entries, one per criterion, in order.

DO NOT OUTPUT ANYTHING OTHER THAN JSON.
`;
