/**
 * Shared verifier types for trajectories, rubrics, evidence, and results.
 *
 * The verifier consumes saved trajectories instead of a live browser. DOM and
 * Hybrid runs preserve tool-return text/JSON evidence, while CUA runs preserve
 * screenshots sent to the provider plus independent harness probes.
 */
import type { LLMClient } from "../llm/LLMClient.js";
import type { LogLine } from "../types/public/logs.js";

/** Token usage for one or more LLM calls. Matches AgentResult.usage shape. */
export interface TrajectoryUsage {
  input_tokens: number;
  output_tokens: number;
  reasoning_tokens?: number;
  cached_input_tokens?: number;
  inference_time_ms?: number;
}

/** A single criterion in a Stagehand rubric. */
export interface RubricCriterion {
  /** Short name of the criterion (e.g., "Add ground beef to cart"). */
  criterion: string;
  /** What to evaluate and how to award partial credit. */
  description: string;
  /** Maximum points for this criterion. */
  maxPoints: number;
  /**
   * Applicability rule for situational criteria. When this condition is not
   * met, the criterion is excluded from scoring rather than counted as failed.
   */
  condition?: string;
}

/** A rubric — list of criteria for a task. */
export interface Rubric {
  items: RubricCriterion[];
}

/**
 * Spec for a single task being verified. Carried both at runtime and into the
 * verifier alongside the trajectory.
 */
export interface TaskSpec {
  /** Stable identifier (e.g., "united_13" for WebTailBench, task_id for Mind2Web). */
  id: string;
  /** Task instruction shown to the agent. */
  instruction: string;
  /** Starting URL, if any. */
  initUrl?: string;
  /** Rubric carried by the dataset or generated by a verifier backend. */
  precomputedRubric?: Rubric;
  /** Optional reference answer (set when dataset ships one). */
  expectedAnswer?: string;
}

/**
 * A single modality unit in tier-1 agent evidence. Mirrors the shape of
 * ModelMessage content parts so we can reproduce what the LLM ingested.
 */
export type AgentEvidenceModality =
  | { type: "text"; content: string }
  | { type: "image"; bytes: Buffer; mediaType: string }
  | { type: "json"; content: unknown };

/**
 * Tier 1 — exactly the bytes/strings/objects the agent's LLM ingested as the
 * tool result for this step.
 *
 * Modes:
 *   - CUA: usually a single image modality (the screenshot sent to the provider).
 *   - Hybrid: tool result with optional screenshotBase64 → one image + one text.
 *   - DOM: tool returns (extract JSON, ariaTree text, etc.) → text/json modalities.
 */
export interface AgentEvidence {
  modalities: AgentEvidenceModality[];
}

/**
 * Tier 2 — independent harness probes around this step.
 *
 * If a probe wasn't captured, the field is absent (not null).
 */
export interface ProbeEvidence {
  /** URL after the step's tool execution. */
  url?: string;
  /**
   * Bus screenshot captured after the step. Path on disk is preferred once
   * persisted; in-memory Buffer is used during a live run.
   */
  screenshot?: Buffer;
  /** Reference to the persisted screenshot file under the trajectory dir. */
  screenshotPath?: string;
  /** Viewport scroll context. Lets the verifier reason about whether the agent saw the full page. */
  scroll?: { top: number; pageHeight: number };
  /** Accessibility tree snapshot. */
  ariaTree?: string;
  /** Verifier-requested probes, keyed by criterion id. */
  onDemand?: Record<string, unknown>;
}

/** Outcome of a single tool execution as seen by the harness. */
export interface ToolOutput {
  ok: boolean;
  /**
   * The tool's return value. Same payload that flowed into agentEvidence
   * modalities, but in its native shape (e.g., the extract result, the act
   * describe-string) rather than serialized for the LLM.
   */
  result: unknown;
  error?: string;
}

/** One step in a trajectory: action + reasoning + evidence + outcome. */
export interface TrajectoryStep {
  index: number;
  actionName: string;
  actionArgs: Record<string, unknown>;
  /** From AgentAction.reasoning. May be empty for tools that don't surface reasoning. */
  reasoning: string;
  agentEvidence: AgentEvidence;
  probeEvidence: ProbeEvidence;
  toolOutput: ToolOutput;
  /** ISO 8601 timestamp when the step's tool execution started. */
  startedAt: string;
  /** ISO 8601 timestamp when the step's tool execution finished. */
  finishedAt: string;
}

/** Terminal status of the agent run. */
export type TrajectoryStatus = "complete" | "aborted" | "stalled" | "error";

/**
 * Full trajectory for one task run.
 *
 * The on-disk layout is one directory per task:
 *
 *   .trajectories/<run-id>/<task-id>/
 *     ├── task_data.json           — TaskSpec + result metadata
 *     ├── trajectory.json          — this object, with image paths instead of bytes
 *     ├── screenshots/
 *     │   ├── probe/<N>.png        — tier-2 probe screenshot per step
 *     │   └── agent/<N>.png        — tier-1 image the model received per step
 *     ├── scores/
 *     │   └── result.json          — Result from V3Evaluator.verify()
 *     ├── core.log                 — captured action log
 *     └── times.json               — step timing + token usage
 */
export interface Trajectory {
  task: TaskSpec;
  steps: TrajectoryStep[];
  finalAnswer?: string;
  status: TrajectoryStatus;
  usage: TrajectoryUsage;
  timing: { startedAt: string; endedAt: string };
}

/** A single screenshot kept by Step 1, ready for downstream relevance scoring. */
export interface CanonicalScreenshot {
  /** 0-based position in the kept-screenshots array. Stable across the pipeline. */
  canonicalIndex: number;
  /**
   * Trajectory step index this screenshot came from. Matches
   * `Trajectory.steps[i].index`. Lets downstream prompts cross-reference the
   * action history.
   */
  originalStepIndex: number;
  /** Position of the step in `Trajectory.steps` (0..steps.length-1). */
  trajectoryStepPosition: number;
  /** The resized PNG/JPEG buffer (or native bytes if sharp unavailable). */
  bytes: Buffer;
  /** MIME media type. Always "image/png" after the optional resize. */
  mediaType: string;
  /** Reason this frame was kept: "first" / "last" / "diverges". */
  keptReason: "first" | "last" | "diverges" | "no-dedup";
}

/**
 * A text evidence point sourced from tier-2 probes or tier-1 tool outputs.
 * These feed the same relevance + scoring path as screenshots, letting DOM
 * and hybrid agents preserve extract/aria/tool-return evidence without a
 * separate verifier architecture.
 */
export interface CanonicalTextEvidence {
  /** 0-based position in the combined evidence-point array. */
  canonicalIndex: number;
  originalStepIndex: number;
  trajectoryStepPosition: number;
  /** Where the text came from. */
  source: "probe-aria" | "agent-text" | "agent-json" | "tool-output";
  /** The text payload, already truncated. */
  content: string;
}

export type CanonicalEvidence = CanonicalScreenshot | CanonicalTextEvidence;

/** Result of Step 1 evidence loading. */
export interface EvidenceLoadResult {
  /** Kept frames, in chronological order. */
  screenshots: CanonicalScreenshot[];
  /**
   * Maps `Trajectory.steps[i].index` → canonical index in `screenshots`. Step
   * indices that were deduplicated point to the surviving canonical frame
   * (typically the prior kept frame). Useful for "find me the screenshot for
   * step K" lookups in downstream prompts.
   */
  stepIndexToCanonical: Map<number, number>;
  /** Number of original frames considered. */
  originalCount: number;
  /** Number of frames kept post-dedup (== screenshots.length). */
  keptCount: number;
  /** Effective thresholds used (resolved from env). */
  thresholds: {
    ssim: number;
    mse: number;
    resize: number;
  };
}

/** Options for evidence loading. Mainly env override hooks for tests. */
export interface EvidenceLoadOptions {
  /** Override VERIFIER_SSIM_THRESHOLD. */
  ssimThreshold?: number;
  /** Override VERIFIER_MSE_THRESHOLD. */
  mseThreshold?: number;
  /** Override VERIFIER_IMAGE_RESIZE. */
  imageResize?: number;
}

/** Score for a single rubric criterion after evidence analysis + rescoring. */
export interface CriterionScore {
  /** Matches RubricCriterion.criterion (the criterion's short name). */
  criterion: string;
  /** Maximum possible points for this criterion. */
  maxPoints: number;
  /**
   * Points earned after evidence analysis. Null when the criterion is
   * conditional and its condition was not met — excluded from both numerator
   * and denominator in the process score.
   */
  earnedPoints: number | null;
  /** Verifier's explanation for the score. */
  explanation: string;
  /**
   * True if the criterion is conditional and its condition was determined to
   * be met. Absent for non-conditional criteria.
   */
  conditionMet?: boolean;
  /**
   * Set when the verifier had no evidence to ground this criterion in either
   * tier. Treated as uncontrollable failure (full credit) but surfaced here
   * so dashboards can flag low-confidence results.
   */
  evidenceInsufficient?: boolean;
}

/**
 * Earliest step where the agent's trajectory went off-track, classified
 * against the error taxonomy (7 top-level categories, 1.1–7.4 sub-codes).
 */
export interface FirstPointOfFailure {
  stepIndex: number;
  /** Sub-code from the error taxonomy (e.g., "2.3" for a specific hallucination type). */
  errorCode: string;
  /** Top-level category name (Selection, Hallucination, etc.). */
  category: string;
  /** Verifier's reasoning for selecting this point. */
  description?: string;
}

/**
 * Structured observation surfaced by the verifier that another agent or
 * tooling could act on. Findings are emitted opportunistically by Step 8
 * (outcome verification) when the verifier notices actionable patterns —
 * repeated tool-call failures, ambiguous task specs, evidence gaps, etc.
 *
 * Not produced for every task: when nothing actionable surfaces, the
 * `findings` array on the EvaluationResult is empty. Consumers should treat the
 * field as advisory, not as part of the formal score.
 */
export interface VerifierFinding {
  /**
   * Category of the observation. Open-ended enum — additional categories may
   * be added as verifier backends surface new failure modes.
   */
  category:
    | "agent_tool_usage" // agent's tool calls had repeated issues (misclicks, wrong args, retries)
    | "agent_strategy" // higher-level planning / decision-making problems
    | "rubric_quality" // criteria were overly strict, ambiguous, or contradictory
    | "trajectory_capture" // gaps in evidence (missing screenshots, empty steps)
    | "task_specification" // task instruction was ambiguous / under- or over-specified
    | "verifier_uncertainty" // verifier itself couldn't confidently decide
    | "other";
  /** Impact: info (FYI), warning (worth investigating), blocking (broke the task). */
  severity: "info" | "warning" | "blocking";
  /** What the verifier noticed. Plain prose, grounded in evidence from the trajectory. */
  description: string;
  /**
   * Optional concrete next action another agent could take. Should be
   * specific enough that it can be acted on without further reasoning —
   * e.g., "Try double_click instead of triple_click to clear placeholder
   * text on this form field."
   */
  suggestedAction?: string;
  /** Step indices in the trajectory where this pattern showed up. */
  relatedSteps?: number[];
}

/** Stable debugging summary emitted by verifier backends. */
export interface VerifierRawSteps {
  backend?: "legacy" | "verifier";
  reason?: string;
  primaryIntent?: string;
  reasoning?: string;
  rubricSource?: "precomputed" | "generated" | "none";
  approach?: "a" | "b";
  optionalsMode?: "folded" | "separate" | "skip";
  totalEarned?: number;
  totalMax?: number;
  evidenceImages?: number;
  evidenceTexts?: number;
  evidenceOriginalScreenshots?: number;
  legacyEvaluation?: string;
  screenshotCount?: number;
}

/** Task-validity classification: whether the task is even answerable. */
export interface TaskValidity {
  /** True if the task is underspecified / has multiple valid interpretations. */
  isAmbiguous: boolean;
  /** Human-readable ambiguity explanation when available. */
  ambiguityReason?: string;
  /** True if the task is impossible / illegal / NSFW / otherwise infeasible. */
  isInvalid: boolean;
  /** Human-readable invalid-task explanation when available. */
  invalidReason?: string;
  /** Optional sub-codes from the task-classification taxonomy. */
  ambiguityCodes?: string[];
  invalidTaskCodes?: string[];
}

/**
 * Evaluator output. Legacy evaluation may only populate outcome fields; richer
 * verifier backends can also populate process scoring and diagnostics.
 *
 * Process and outcome are deliberately independent when both are present:
 * an agent can follow the right steps but get blocked (high process, low
 * outcome), or succeed through an unexpected path (variable process, high
 * outcome).
 */
export interface EvaluationResult {
  /** Did the agent accomplish the task from the user's perspective? */
  outcomeSuccess: boolean;
  /** Human-readable explanation for the outcome. */
  explanation?: string;
  /** Aggregated earned/max across applicable criteria, in [0, 1]. */
  processScore?: number;
  /** Per-criterion breakdown after rescoring. */
  perCriterion?: CriterionScore[];
  /** Step 9a — first step where the trajectory went off-track, if any. */
  firstPointOfFailure?: FirstPointOfFailure;
  /** Step 10 — task-itself ambiguity / validity. */
  taskValidity?: TaskValidity;
  /**
   * Ids (RubricCriterion.criterion strings) of criteria where neither tier of
   * evidence resolved the question. Treated as uncontrollable → full credit,
   * but flagged here so consumers can decide whether to discount the score.
   */
  evidenceInsufficient?: string[];
  /**
   * Structured observations from the verifier that a downstream tool or
   * follow-up agent could act on. Opportunistic — empty when the verifier
   * doesn't notice anything actionable. Not part of the score; advisory.
   */
  findings?: VerifierFinding[];
  /** Debugging summary from the active evaluator backend. */
  rawSteps?: VerifierRawSteps;
}

/**
 * Verifier interface. Implementations consume a Trajectory + TaskSpec and
 * return an EvaluationResult — they MUST NOT touch a live browser.
 */
export interface Verifier {
  verify(trajectory: Trajectory, taskSpec: TaskSpec): Promise<EvaluationResult>;
}

export interface RubricVerifierOptions {
  /** Factory that returns a configured LLMClient. Called per pipeline step so callers can supply step-specific clients. */
  getClient: () => LLMClient;
  /** Logger; defaults to a no-op so the verifier stays quiet inside V3Evaluator. */
  logger?: (line: LogLine) => void;
}

export interface ErrorTaxonomySubCategory {
  /** Sub-code (e.g., "2.3"). */
  code: string;
  /** Human-readable name (e.g., "Output fabrication"). */
  name: string;
  /** Detailed description ported from the .md. Markdown formatting preserved. */
  description: string;
}

export interface ErrorTaxonomyCategory {
  /** Top-level number (1-8). */
  number: number;
  /** Top-level name (e.g., "Hallucination Errors"). */
  name: string;
  /** One-sentence summary of the category. */
  summary: string;
  /** Sub-categories. The last one is always an "Other" catch-all. */
  subCategories: ErrorTaxonomySubCategory[];
}

export interface ParseFailureStepNumbersOptions {
  /**
   * Maximum unique step numbers to expand from ranges. Protects the verifier
   * from malformed model output such as "0-2147483647".
   */
  maxExpandedSteps?: number;
  /** Optional inclusive upper bound for accepted step numbers. */
  maxStep?: number;
}
